config/routes.rb
Knack::Application.routes.draw do

  match "direction/demo"

  devise_for :users
  root :to => 'app#app_home'

  match 'direction/redirect'
  match 'coder/getoption'
  match 'grammarian/getoption'
  match 'grammarian/elu_consumer'
  match 'mathematician/getoption'
  match 'mathematician/maths_consumer'
  match 'admins/getoption'
  match 'admins/server_fault_consumer'
  match 'admins/getoption'
  match 'admins/super_user_consumer'
  match 'admins/getoption'
  match 'admins/ask_ubuntu_consumer'
  match 'coder/sof_consumer'
  match 'coder/git_consumer'
  match 'coder/blog_consumer'
  match 'coder/bit_b_consumer'
  match 'coder/linked_in_consumer'
  match 'coder/programmers_consumer'

  match 'message' => 'message#new', :as => 'message', :via => :get
  match 'message' => 'message#create', :as => 'message', :via => :post

  match "*path" => redirect("/")

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => {:with => %r{.+@.+\..+}}, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController

  before_filter :authenticate_user!

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      flash.now[:success] = "Email sent successfully"
      redirect_to direction_redirect_url
    else
      flash.now[:error] = "Please fill the required fields."
      render :new
    end


  end

end

app/views/message/_message_footer.html.erb
<footer class="footer">
  <small>
    <p> ©2015 codebeats, All rights not reserved. </p>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", "/message" %></li>
      <li><a href="http://praaveenvr.blogspot.com">Blogs</a></li>
    </ul>
  </nav>
</footer>

app/views/message/new.html.erb
<!DOCTYPE html>
<html>

<head>
  <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/assets/favicon.ico" type="image/x-icon">
  <style>
      #new_message INPUT {
          height: 38px;
          width: 365px;
      }

      h1, label {
          color: #ffffff;
      }

      h3 {
          color: #ffffff;
          text-align: center;
      }

      h1 a {
          color: #ffffff;
      }

      .links a {
          color: #ffffff;
      }

      .col-md-5 h2 {
          color: #ffffff;
      }

      .contact {
          display: inline-block;
      }

      .label_align {
          font-size: 100%;
          float: right;
          clear: both;
      }

      .head {
          text-align: right;
      }

      .back p {
          text-align: right;
          color: #ffffff;
      }

      p {
          color: #ffffff;
      }

      .page-header {
          text-align: right;
      }

      footer {
          margin-top: 615px;
          padding-top: 25px;
          border-top: 1px solid #eaeaea;
          /*color: #999;*/
      }

      footer a {
          color: #ffffff;
      }

      footer p {
          color: #ffffff;
      }

      footer a:hover {
          color: #000000;
      }

      footer small {
          float: left;
      }

      footer ul {
          float: right;
          list-style: none;
      }

      footer ul li {
          float: left;
          margin-left: 10px;
      }
  </style>
</head>

<body style="background-color:#1175BF ">

<div class="container">
  <div class="col-md-5 contact">
    <h2>Contact form</h2>
    <%= form_for @message, :url => message_path do |form| %>
        <% @message.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>

        <fieldset class="fields">
          <div class="field">
            <div class="label_align"><%= form.label :name %></div>
            <%= form.text_field :name, :autofocus => true %>
          </div>

          <div class="field">
            <div class="label_align"><%= form.label :email %></div>
            <%= form.text_field :email %>
          </div>
          <div class="field">
            <div class="label_align"><%= form.label :subject %></div>
            <%= form.text_field :subject %>
          </div>

          <div class="field">
            <div class="label_align"><%= form.label :body %></div>
            <%= form.text_field :body %>
          </div>
        </fieldset>

        <fieldset class="actions">
          <%= form.submit "Send" %>
        </fieldset>
    <% end %>
  </div>
  <div class="col-md-7 contact">
    <div class="head"><h1><%= link_to "KnacK", '/' %> </h1></div>
    <div class="back"><p><%= link_to "past", '/direction/redirect' %></p></div>

    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Upcoming works</h1>
      </div>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="https://www.blogger.com/features">
          <img class="img-responsive" src="/assets/gra.png" alt="">
        </a>
      </div>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="#">
          <img class="img-responsive" src="/assets/su.png" alt="">
        </a>
      </div>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="#">
          <img class="img-responsive" src="/assets/wa.png" alt="">
        </a>
      </div>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="#">
          <img class="img-responsive" src="/assets/sf-logo.png" alt="">
        </a>
      </div>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="#">
          <img class="img-responsive" src="/assets/uanl.png" alt="">
        </a>
      </div>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="#">
          <img class="img-responsive" src="/assets/twit.png" alt="">
        </a>
      </div>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="#">
          <img class="img-responsive" src="/assets/Quora.png" alt="">
        </a>
      </div>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="#">
          <img class="img-responsive" src="/assets/maths.jpg" alt="">
        </a>
      </div>
    </div>
  </div>
  <%= render "message_footer" %>
</div>


</body>

</html>